//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyQuizAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long FeedbackId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public Nullable<long> ErrorId { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Accepted { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
