//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyQuizAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyReport
    {
        public long ReportId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> SubjectCount { get; set; }
        public Nullable<long> TestCount { get; set; }
        public Nullable<long> CorrectAnswer { get; set; }
        public Nullable<long> WrongAnswer { get; set; }
    
        public virtual User User { get; set; }
    }
}
